const actionNames = {
  RESET_STATE: 'RESET_STATE',
  SET_SELECTED_IMAGE_DATASET: 'SET_SELECTED_IMAGE_DATASET',
  SET_TABLE_SETTINGS: 'SET_TABLE_SETTINGS',
  SET_SUMMARY_DATASETS: 'SET_SUMMARY_DATASETS',
  SET_CLINICAL_DATASETS: 'SET_CLINICAL_DATASETS',
  SET_EXPERIMENTAL_DATASETS: 'SET_EXPERIMENTAL_DATASETS',

};

export default actionNames;