const actionNames = {
  RESET_STATE: 'RESET_STATE',
  SET_SELECTED_IMAGE_DATASET: 'SET_SELECTED_IMAGE_DATASET',
  SET_TABLE_SETTINGS: 'SET_TABLE_SETTINGS',
  SET_SUMMARY_DATASETS: 'SET_SUMMARY_DATASETS',
  SET_CLINICAL_DATASETS: 'SET_CLINICAL_DATASETS',
  SET_EXPERIMENTAL_DATASETS: 'SET_EXPERIMENTAL_DATASETS',
  SET_DATA_TYPE_COUNTS: 'SET_DATA_TYPE_COUNTS',
  SET_TOTAL_FILE_COUNT: 'SET_TOTAL_FILE_COUNT',
  SET_SELECTED_PARTICIPANT: 'SET_SELECTED_PARTICIPANT'
};

export default actionNames;